name: Resize Image

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  sanitize-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Resize Image
        uses: VishnuSanal/img-resize-action@88afe53cf94786138c755763b2b3d1681b463a33
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          width: 600
          height: 800
