on:
  issue_comment:
    types: [created, edited]

jobs:
  sanitize-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Resize Image
        uses: VishnuSanal/img-resize-action@6ef8d819165251d1c92d78bcb94e311a886491d4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          width: 800
          height: 600
