name: Resize Image

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  sanitize-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Resize Image
        uses: VishnuSanal/img-resize-action@13b9b5a7236b39a1eeda6a79517a990c86a2f65f
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          width: 600
          height: 800